# build.ps1  --  Assemble src/ into a single production index.html.
#
#   DEV : edit files in src\, open src\index.dev.html in a browser to test.
#   PROD: run  .\build.ps1  then deploy the generated index.html.
#
# First run on a machine may need:  Set-ExecutionPolicy -Scope CurrentUser RemoteSigned
$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot

function ReadRaw($rel) { [System.IO.File]::ReadAllText((Join-Path $root $rel), [System.Text.Encoding]::UTF8) }

$tpl = ReadRaw 'src\index.dev.html'
$css = ReadRaw 'src\styles.css'
$js  = ReadRaw 'src\app.js'

# Inline the two local assets. .Replace() is a literal (non-regex) swap, so the
# JS template-literal backticks and ${...} in app.js pass through untouched.
$tpl = $tpl.Replace('<link rel="stylesheet" href="./styles.css">', "<style>`r`n$css`r`n</style>")
$tpl = $tpl.Replace('<script src="./app.js"></script>',            "<script>`r`n$js`r`n</script>")

$banner = "<!-- GENERATED by build.ps1 - DO NOT EDIT. Edit files in src\ and rebuild. -->`r`n"
$out    = $banner + $tpl

# UTF-8 without BOM (Thai-safe, avoids a stray BOM at the top of the HTML).
[System.IO.File]::WriteAllText((Join-Path $root 'index.html'), $out, (New-Object System.Text.UTF8Encoding($false)))

$size = (Get-Item (Join-Path $root 'index.html')).Length
Write-Host ("Built index.html: {0:N0} bytes" -f $size) -ForegroundColor Green
